version: "3.9"

services:
  redis:
    image: arm64v8/redis:${redis_version}
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=rootroot
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - default

  redis-exporter:
    image: bitnami/redis-exporter:${redis_exporter_version}
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=rootroot
    expose:
      - 9121
    networks:
      - default

  rabbitmq:
    image: arm64v8/rabbitmq:${rabbitmq_version}
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    expose:
      # prometheus
      - 15692
    ports:
      # management-ui
      - "15672:15672"
      - "5672:5672"
    networks:
      - default

  postgresql:
    image: arm64v8/postgres:${postgresql_version}
    environment:
      - POSTGRES_PASSWORD=rootroot
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - default

  postgresql-exporter:
    image: bitnami/postgres-exporter:${postgresql_exporter_version}
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:rootroot@postgresql:5432/postgres?sslmode=disable
    expose:
      - 9187
    networks:
      - default

  mysql:
    image: arm64v8/mysql:${mysql_version}
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
    expose:
      - 3306
    ports:
      - "3306:3306"
    networks:
      - default

  mysql-exporter:
    image: bitnami/mysqld-exporter:${mysql_exporter_version}
    environment:
      - DATA_SOURCE_NAME=root:rootroot@(mysql:3306)
    expose:
      - 9104
    networks:
      - default

  mongodb:
    image: arm64v8/mongo:${mongodb_version}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootroot
      - MONGO_INITDB_DATABASE=mongo
    expose:
      - 27017
    ports:
      - "27017:27017"
    networks:
      - default

  grafana:
    image: bitnami/grafana:${grafana_version}
    ports:
      - "3000:3000"
    networks:
      - default
    depends_on:
      - prometheus

  loki:
    image: bitnami/grafana-loki:${loki_version}
    expose:
      - 3100
    ports:
      - "3100:3100"
    networks:
      - default

  prometheus:
    image: bitnami/prometheus:${prometheus_version}
    expose:
      - 9090
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - default

networks:
  default:
